
version: 0.1

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - aws s3 cp build s3://abi-brgrbldr --recursive
artifacts:
  discard-paths: yes